# generated by zon2nix (https://github.com/nix-community/zon2nix),
# with release-asset URLs replaced by the canonical GitHub release URLs.

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "12203844d9f0467cc4bca712f6b8ec475415470d6e26bc17c6654ae5e6de6c7d44a1";
    path = fetchzip {
      url = "https://github.com/Syndica/boringssl-zig/archive/c53df00d06b02b755ad88bbf4d1202ed9687b096.tar.gz";
      hash = "sha256-I6ST8fEQ35At/cRxjXJGxDiqZHhoJnW9n7GrhpO6RmE=";
    };
  }
  {
    name = "zenai-0.0.0-iOY_VAOpBQBL1tO2StxVzubQcM1DliSYIQEkqS5s_kWj";
    path = fetchzip {
      url = "https://github.com/gotlougit/zenai/archive/8e82177ac06b3228c94d6ca27d90aca8a839c4d0.tar.gz";
      hash = "sha256-xQ5QSaV1omdoV+xQNfwC4p2o1VyHOZaHpNIBJearg3Q=";
    };
  }
  {
    name = "1220fe8ebe4b59e92c1c36246904a92dbbba3111c5be53d44488a46049d0c9391719";
    path = fetchzip {
      url = "https://github.com/arrufat/isocline/archive/832a9fe25f5f4458fcc47b5acc7c21db669c2f47.tar.gz";
      hash = "sha256-+yuUydbMaraJIjIAJ31hTxnT6voPG81odE/+7fe6+Ak=";
    };
  }
  {
    name = "N-V-__8AABDOXwDW4TLrTiydikRCN2ym9hJI1GKGR09ZLBvY";
    path = fetchzip {
      url = "https://pkg.lightpanda.io/chromium/depot_tools.git-4ce8ba39a3488397a2d1494f167020f21de502f3.tar.gz";
      hash = "sha256-WTzjmLFjh1yDDEvYE7Qfx8aBxMLdATx14+Jprwh8ZgQ=";
    };
  }
  {
    name = "N-V-__8AADGOTAg2qy2JMjVSleelXVWZhf9UTIjkuioQsv9-";
    path = fetchgit {
      url = "https://github.com/google/boringssl";
      rev = "535cc391915c37912ff9b3edb0cff9b3c5c77db0";
      hash = "sha256-rSmfL4FC9QgIsQJWHwGlHuAR1ntHrK271A392FacQrs=";
    };
  }
  {
    name = "N-V-__8AAHM9RQHjzJo8Wn4dbGPqNOC21zZJJA9PcCj7FPF5";
    path = fetchzip {
      url = "https://github.com/curl/curl/releases/download/curl-8_20_0/curl-8.20.0.tar.gz";
      hash = "sha256-OwZ/VH6lpD0DNoOA1pA1SWnmtitigklwlwHd3EOLnkc=";
    };
  }
  {
    name = "N-V-__8AAJ2cNgAgfBtAw33Bxfu1IWISDeKKSr3DAqoAysIJ";
    path = fetchzip {
      url = "https://github.com/madler/zlib/releases/download/v1.3.2/zlib-1.3.2.tar.gz";
      hash = "sha256-tKLefmGqB2HVUMILJ7Gqa0v9GH7fqv64d5S5kK1tcYU=";
    };
  }
  {
    name = "N-V-__8AAJudKgCQCuIiH6MJjAiIJHfg_tT_Ew-0vZwVkCo_";
    path = fetchzip {
      url = "https://github.com/google/brotli/archive/028fb5a23661f123017c060daa546b55cf4bde29.tar.gz";
      hash = "sha256-kl8ZHt71v17QR2bDP+ad/5uixf+GStEPLQ5ooFoC5i8=";
    };
  }
  {
    name = "N-V-__8AALNYqgDpBBECZ3Jn_VpVGjX4xX7uTSZg00tYjmy3";
    path = fetchzip {
      url = "https://sqlite.org/2025/sqlite-amalgamation-3510000.zip";
      hash = "sha256-1eXn/OLxdSGHE2sBl0x/goNF/gmfAJbl2DaNtoDqkdo=";
    };
  }
  {
    name = "N-V-__8AAMHpvwChC6orFCDB8MeiumT6OlfmKfmrWlak7Int";
    path = fetchzip {
      url = "https://github.com/nghttp2/nghttp2/releases/download/v1.69.0/nghttp2-1.69.0.tar.gz";
      hash = "sha256-NDGar8b4VFdzIX1OrvXwaRH9Z9EEHdxTRwk4HsZDVQg=";
    };
  }
  {
    name = "sqlite3-3.51.0-DMxLWssOAABZ8cAvU_LfBIbp0kZjm824PU8sSLXpEDdr";
    path = fetchzip {
      url = "https://github.com/allyourcodebase/sqlite3/archive/8f840560eae88ab66668c6827c64ffbd0d74ef37.tar.gz";
      hash = "sha256-idsiL4KInV1UZPax6SkUnk8bQEet1EgcyuSY/B9ToII=";
    };
  }
  {
    name = "v8-0.0.0-xddH6_vtAgAdI8KeSyuBCgVOEFDN_0BfMekjdP6fkRqk";
    path = fetchzip {
      url = "https://github.com/lightpanda-io/zig-v8-fork/archive/refs/tags/v0.5.1.tar.gz";
      hash = "sha256-FF7qcwid5PDXgyBKtvGBpawNNTuhuAhjWpCYqjHlnGY=";
    };
  }
]
